# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09fcc2a5c7f2301649d79e7cf91eac6e"
name = "AutoTrackDev"
application_url = "https://seriously-hints-ordered-separated.trycloudflare.com"
embedded = true
handle = "trackdrop"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "trackauto.myshopify.com"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "https://app.theautotrack.com/api/webhooks/customers-data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://app.theautotrack.com/api/webhooks/customers-redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://app.theautotrack.com/api/webhooks/shop-redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_content,read_customers,read_fulfillments,read_inventory,read_locations,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_themes,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_content,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_themes,write_third_party_fulfillment_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://seriously-hints-ordered-separated.trycloudflare.com/auth/callback",
  "https://seriously-hints-ordered-separated.trycloudflare.com/auth/shopify/callback",
  "https://seriously-hints-ordered-separated.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://seriously-hints-ordered-separated.trycloudflare.com/track"
subpath = "track"
prefix = "a"

[pos]
embedded = false
