<?php

namespace App\Console\Commands;


use App\Http\Controllers\ProductController;
use App\Models\ErrorMessage;
use App\Models\Session;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Mail;

class createUpdateAutoGeneratedProductsCron extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'create_update_auto_generated_products:cron';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {

        try {
            Session::orderBy('id')->chunk(50, function ($sessions) {
                foreach ($sessions as $session) {
                    $product_controller = new ProductController();
                    $product_controller->auto_generated_products($session);
                }
            });
//            $msg = new ErrorMessage();
//            $msg->message = 'create update auto generated products ';
//            $msg->save();
        }catch (\Exception $exception){
            $msg = new ErrorMessage();
            $msg->message = 'error in create update auto generated products : '.json_encode($exception->getLine());
            $msg->save();
        }
        return 0;
    }
}
